name: ahl
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  indicator_button:
    git: https://github.com/Josephincrafter/indicator_button.git
  flutter:
    sdk: flutter
  flutter_bloc: any
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: any
  web: ^0.3.0
  transparent_image: ^2.0.0
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/butler/Butler_Regular.otf
        - asset: assets/fonts/butler/Butler_Ultra_Light.otf
          weight: 100
        - asset: assets/fonts/butler/Butler_Ultra_Light.otf
          weight: 200
        - asset: assets/fonts/butler/butler_medium.otf
          weight: 500
        - asset: assets/fonts/butler/Butler_Bold.otf
          weight: 600
        - asset: assets/fonts/butler/Butler_Black.otf
          weight: 700
        - asset: assets/fonts/butler/butler_extra_bold.otf
          weight: 800

    - family: Aileron
      fonts:
        - asset: assets/fonts/aileron/Aileron-Regular.otf
        - asset: assets/fonts/aileron/Aileron-UltraLight.otf
          weight: 100
        - asset: assets/fonts/aileron/Aileron-Thin.otf
          weight: 200
        - asset: assets/fonts/aileron/Aileron-Light.otf
          weight: 300
        - asset: assets/fonts/aileron/Aileron-SemiBold.otf
          weight: 600
        - asset: assets/fonts/aileron/Aileron-Bold.otf
          weight: 700
        - asset: assets/fonts/aileron/Aileron-Black.otf
          weight: 800
        - asset: assets/fonts/aileron/Aileron-Heavy.otf
          weight: 900

    - family: Alegreya
      fonts:
        - asset: assets/fonts/alegreya/AlegreyaSans-Regular.ttf
